apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - name: pod1
    image: nginx:alpine
    resources: {}
    env:
    - name: TREE1
      valueFrom:
        configMapKeyRef:
          name: trauerweide
          key: tree
    volumeMounts:
    - name: birke-vol
      mountPath: /etc/birke
  volumes:
  - name: birke-vol
    configMap:
      name: birke
  dnsPolicy: ClusterFirst
  restartPolicy: Always
